<?php

return [
    'cities' => [
        'Abbottabad',
        'Ahmedpur East',
        'Arifwala',
        'Attock',
        'Awaran',
        'Badin',
        'Bahawalnagar',
        'Bahawalpur',
        'Bannu',
        'Barkhan',
        'Battagram',
        'Bhakkar',
        'Bhalwal',
        'Burewala',
        'Chakwal',
        'Chaman',
        'Charsadda',
        'Chichawatni',
        'Chiniot',
        'Chishtian',
        'Chitral',
        'Dadu',
        'Daska',
        'Dera Bugti',
        'Dera Ghazi Khan',
        'Dera Ismail Khan',
        'Faisalabad',
        'Farooqabad',
        'Ghotki',
        'Gujranwala',
        'Gujrat',
        'Gwadar',
        'Hafizabad',
        'Hangu',
        'Haripur',
        'Harnai',
        'Hyderabad',
        'Islamabad',
        'Jacobabad',
        'Jalalpur',
        'Jampur',
        'Jaranwala',
        'Jauharabad',
        'Jhang',
        'Jhelum',
        'Kalat',
        'Kamalia',
        'Kamoke',
        'Karachi',
        'Karak',
        'Kasur',
        'Khairpur',
        'Khanewal',
        'Khanpur',
        'Kharan',
        'Khushab',
        'Khuzdar',
        'Kohat',
        'Kohlu',
        'Kot Addu',
        'Kotli',
        'Lahore',
        'Lakki Marwat',
        'Larkana',
        'Lasbela',
        'Layyah',
        'Lodhran',
        'Loralai',
        'Malakand',
        'Mandi Bahauddin',
        'Mardan',
        'Mastung',
        'Mian Channu',
        'Mianwali',
        'Mingora',
        'Mirpur',
        'Mirpur Khas',
        'Multan',
        'Muzaffargarh',
        'Muzaffarabad',
        'Nankana Sahib',
        'Narowal',
        'Naseerabad',
        'Naushahro Feroze',
        'Nowshera',
        'Okara',
        'Pakpattan',
        'Panjgur',
        'Pattoki',
        'Peshawar',
        'Quetta',
        'Rahim Yar Khan',
        'Rajanpur',
        'Rawalpindi',
        'Sadiqabad',
        'Sahiwal',
        'Sanghar',
        'Sangla Hill',
        'Sargodha',
        'Shahdadkot',
        'Sheikhupura',
        'Shikarpur',
        'Shujaabad',
        'Sialkot',
        'Sibi',
        'Skardu',
        'Sukkur',
        'Swabi',
        'Swat',
        'Tando Adam',
        'Tando Allahyar',
        'Tando Muhammad Khan',
        'Tank',
        'Thatta',
        'Timergara',
        'Toba Tek Singh',
        'Turbat',
        'Umerkot',
        'Vehari',
        'Wah Cantonment',
        'Wazirabad',
        'Zhob',
        'Ziarat',
    ],
];
